import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sidebar";
import { GeistSans } from "geist/font/sans";
import { cn } from "@/lib/utils";
import { BackgroundBeams } from "@/components/background-beams";
import ConvexClientProvider from "@/components/convex-client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConvexClientProvider>
        <body className={cn(GeistSans.className, "transform-gpu h-screen")}>
          <Navbar />{" "}
          <div className="absolute top-0 z-[-2] h-screen w-screen bg-[#000000] bg-[radial-gradient(#ffffff33_1px,#00091d_1px)] bg-[size:20px_20px]"></div>{" "}
          {children} <BackgroundBeams />
        </body>
      </ConvexClientProvider>
    </html>
  );
}
